# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SASURL: ''

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./Hackathon2024
      run: dotnet restore
    - name: Build
      working-directory: ./Hackathon2024
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Hackathon2024
      run: dotnet test --no-build --verbosity normal
    - name: Performance
      working-directory: ./Hackathon2024
      run: dotnet run --configuration Release --project Hackathon2024.Benchmark/Hackathon2024.Benchmark.csproj -- ${GITHUB_REF##*/} $SASURL
